name: myenv
channels:
  - conda-forge
dependencies:
  - pangeo-notebook==2020.05.10
  - netcdf4
  - dask
  - matplotlib
  - xarray
  - hvplot
  - fsspec
  - s3fs
  - holoviews
  - cartopy
  - zarr
  - datashader
  - intake
  - intake-esm

